[build]
  command = "pip install -r backendapi/requirements.txt && npm install && npm run build"
  publish = "build"  # Specify the directory that contains the final build

[build.environment]
  PYTHON_VERSION = "3.9"  # or your project's required version
  NODE_VERSION = "16"      # or your project's required version

[build.lifecycle]
  onBuild = "echo 'Running custom build commands...'"  # Optional